#!/bin/bash
set -e

echo "=== Pack50 Bot Configuration ==="
echo ""

# Generate random passwords
DB_PASSWORD=$(openssl rand -hex 16)
REDIS_PASSWORD=$(openssl rand -hex 16)
ENCRYPTION_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -base64 32)
DEFAULT_ADMIN_PASSWORD=$(openssl rand -base64 12)

# Interactive prompts
echo "Please provide the following configuration:"
echo ""

read -p "Telegram Bot Token: " BOT_TOKEN
read -p "Anthropic API Key (optional): " ANTHROPIC_API_KEY
read -p "OpenAI API Key (optional): " OPENAI_API_KEY
read -p "Webhook URL (optional, for production): " WEBHOOK_URL

# Generate webhook secret if URL provided
if [ -n "$WEBHOOK_URL" ]; then
    WEBHOOK_SECRET=$(openssl rand -hex 32)
else
    WEBHOOK_SECRET=""
fi

# Create .env file
cat > .env << EOF
# Generated by configure.sh on $(date)

# Telegram Bot Configuration
BOT_TOKEN=$BOT_TOKEN

# Database Configuration (auto-generated)
DB_PASSWORD=$DB_PASSWORD

# Redis Configuration (auto-generated)
REDIS_PASSWORD=$REDIS_PASSWORD

# AI Configuration
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
OPENAI_API_KEY=$OPENAI_API_KEY

# Application Configuration
NODE_ENV=production
PORT=3000

# Webhook Configuration
WEBHOOK_URL=$WEBHOOK_URL
WEBHOOK_SECRET=$WEBHOOK_SECRET

# Admin Panel Security (auto-generated)
ENCRYPTION_KEY=$ENCRYPTION_KEY
JWT_SECRET=$JWT_SECRET
DEFAULT_ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD
EOF

# Set secure permissions
chmod 600 .env

echo ""
echo "✅ Configuration complete!"
echo ""
echo "Generated .env file with secure passwords."
echo ""
echo "⚠️  IMPORTANT: Save these credentials!"
echo "   Admin login: admin / $DEFAULT_ADMIN_PASSWORD"
echo ""
echo "Next step:"
echo "  Run: docker compose up -d"
echo ""
