#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}➜ $1${NC}"
}

print_header() {
    echo -e "${BLUE}================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}================================================${NC}"
}

echo ""
print_header "Pack50 VDS Deployment Script"
echo ""

# Check if running as root (optional but recommended for VDS)
if [ "$EUID" -ne 0 ] && [ -z "$SUDO_USER" ]; then
    print_info "Not running as root. Some commands may require sudo."
fi

# Step 1: Check prerequisites
print_info "Step 1: Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    print_error "Docker not found. Installing Docker..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
    print_success "Docker installed"
else
    print_success "Docker found: $(docker --version)"
fi

if ! command -v docker compose &> /dev/null && ! docker compose version &> /dev/null; then
    print_error "Docker Compose not found"
    exit 1
else
    print_success "Docker Compose found"
fi

if ! command -v git &> /dev/null; then
    print_error "Git not found. Installing git..."
    apt-get update && apt-get install -y git
    print_success "Git installed"
else
    print_success "Git found"
fi

echo ""

# Step 2: Check if we're in pack50 directory or need to clone
print_info "Step 2: Setting up project directory..."

if [ ! -f "docker-compose.prod.yml" ]; then
    if [ -d "pack50" ]; then
        print_info "Found existing pack50 directory"
        cd pack50
    else
        print_info "Cloning repository..."
        git clone https://github.com/Wess21/pack50.git
        cd pack50
        print_success "Repository cloned"
    fi
else
    print_info "Already in pack50 directory"
fi

echo ""

# Step 3: Pull latest code
print_info "Step 3: Pulling latest code from GitHub..."
git fetch origin
git pull origin main || git pull origin master
print_success "Code updated"

echo ""

# Step 4: Check/Create .env file
print_info "Step 4: Checking environment configuration..."

if [ ! -f ".env" ]; then
    print_info "No .env file found. Creating from template..."

    # Generate secure passwords
    DB_PASSWORD=$(openssl rand -hex 16)
    ENCRYPTION_KEY=$(openssl rand -hex 32)
    JWT_SECRET=$(openssl rand -base64 32)
    DEFAULT_ADMIN_PASSWORD=$(openssl rand -base64 12)

    # Interactive prompts
    echo ""
    read -p "Enter Telegram Bot Token: " BOT_TOKEN
    echo ""
    read -p "Enter Anthropic API Key (optional, press Enter to skip): " ANTHROPIC_API_KEY
    read -p "Enter OpenAI API Key (optional, press Enter to skip): " OPENAI_API_KEY
    echo ""
    read -p "Enter Webhook URL (optional, for production webhook mode): " WEBHOOK_URL

    if [ -n "$WEBHOOK_URL" ]; then
        WEBHOOK_SECRET=$(openssl rand -hex 32)
    else
        WEBHOOK_SECRET=""
    fi

    # Create .env file
    cat > .env << EOF
# Generated by deploy-vds.sh on $(date)

# Telegram Bot Configuration
BOT_TOKEN=$BOT_TOKEN

# Database Configuration (auto-generated)
DB_PASSWORD=$DB_PASSWORD

# AI Configuration
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
OPENAI_API_KEY=$OPENAI_API_KEY

# Application Configuration
NODE_ENV=production
PORT=3000

# Webhook Configuration
WEBHOOK_URL=$WEBHOOK_URL
WEBHOOK_SECRET=$WEBHOOK_SECRET

# Admin Panel Security (auto-generated)
ENCRYPTION_KEY=$ENCRYPTION_KEY
JWT_SECRET=$JWT_SECRET
DEFAULT_ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD
EOF

    chmod 600 .env
    print_success ".env file created"

    # Save admin credentials
    echo "$DEFAULT_ADMIN_PASSWORD" > .admin_password
    chmod 600 .admin_password

    echo ""
    print_header "IMPORTANT: Save Admin Credentials"
    echo "Admin Login: admin"
    echo "Admin Password: $DEFAULT_ADMIN_PASSWORD"
    print_info "Password also saved to .admin_password file"
    echo ""
    read -p "Press Enter to continue after saving credentials..."
else
    print_success ".env file exists"
fi

echo ""

# Step 5: Login to GitHub Container Registry
print_info "Step 5: Authenticating with GitHub Container Registry..."
print_info "You need a GitHub Personal Access Token with 'read:packages' permission"
echo ""
echo "To create a token:"
echo "1. Go to https://github.com/settings/tokens/new"
echo "2. Select 'read:packages' scope"
echo "3. Generate token and copy it"
echo ""

read -p "Enter your GitHub username: " GITHUB_USERNAME
read -sp "Enter your GitHub Personal Access Token: " GITHUB_TOKEN
echo ""

if echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin; then
    print_success "Successfully logged in to GitHub Container Registry"
else
    print_error "Failed to login to GHCR"
    exit 1
fi

echo ""

# Step 6: Pull latest image
print_info "Step 6: Pulling latest Docker image from GHCR..."
if docker pull ghcr.io/wess21/pack50:latest; then
    print_success "Latest image pulled"
else
    print_error "Failed to pull image"
    exit 1
fi

echo ""

# Step 7: Stop existing containers (if any)
print_info "Step 7: Stopping existing containers..."
docker compose -f docker-compose.prod.yml down 2>/dev/null || true
print_success "Old containers stopped"

echo ""

# Step 8: Start new containers
print_info "Step 8: Starting new containers..."
if docker compose -f docker-compose.prod.yml up -d; then
    print_success "Containers started"
else
    print_error "Failed to start containers"
    exit 1
fi

echo ""

# Step 9: Wait for services to be healthy
print_info "Step 9: Waiting for services to be healthy..."
sleep 5

max_attempts=30
attempt=0

while [ $attempt -lt $max_attempts ]; do
    if docker compose -f docker-compose.prod.yml ps bot | grep -q "Up"; then
        print_success "Bot is running"
        break
    fi

    attempt=$((attempt + 1))
    echo -n "."
    sleep 2
done

if [ $attempt -eq $max_attempts ]; then
    print_error "Bot failed to start"
    echo ""
    print_info "Recent logs:"
    docker compose -f docker-compose.prod.yml logs --tail=50 bot
    exit 1
fi

echo ""

# Step 10: Test health endpoint
print_info "Step 10: Testing health endpoint..."
sleep 5

if curl -f http://localhost:3000/health -o /dev/null -s; then
    print_success "Health check passed"
else
    print_error "Health check failed"
    echo ""
    print_info "Bot logs:"
    docker compose -f docker-compose.prod.yml logs --tail=50 bot
    exit 1
fi

echo ""

# Step 11: Show status
print_info "Step 11: Container status:"
docker compose -f docker-compose.prod.yml ps

echo ""

# Final summary
print_header "DEPLOYMENT SUCCESSFUL!"
echo ""
print_success "Pack50 bot is now running!"
echo ""
echo "Useful commands:"
echo "  View logs:          docker compose -f docker-compose.prod.yml logs -f"
echo "  Stop bot:           docker compose -f docker-compose.prod.yml down"
echo "  Restart bot:        docker compose -f docker-compose.prod.yml restart bot"
echo "  Update deployment:  ./deploy-vds.sh"
echo ""
echo "Admin Panel:"
echo "  URL: http://$(curl -s ifconfig.me):3000"
echo "  Login: admin"
echo "  Password: (saved in .admin_password file)"
echo ""
print_info "Keep .env and .admin_password files secure!"
echo ""
